"""Update timestamps to use default instead of server_default for SQLite compatibility

Revision ID: 141ad96aa492
Revises: 81b321a41741
Create Date: 2025-06-21 18:30:57.509391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141ad96aa492'
down_revision: Union[str, Sequence[str], None] = '81b321a41741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_foreign_key('fk_conversations_project_id', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_files_filename'))
        batch_op.drop_index(batch_op.f('ix_project_files_project_id'))

    with op.batch_alter_table('project_vm_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_vm_services_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_vm_services_status'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_vm_status'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_vm_status'), ['vm_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('project_vm_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_vm_services_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_vm_services_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_files_filename'), ['filename'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_project_id', type_='foreignkey')
        batch_op.alter_column('is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
