"""Add voice connections and agent voice configuration

Revision ID: 8958bc9e02d2
Revises: 7c581ebfe622
Create Date: 2025-06-18 15:44:30.581718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8958bc9e02d2'
down_revision: Union[str, Sequence[str], None] = '7c581ebfe622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('clarity', sa.Float(), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('api_key_encrypted', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_cloud_proxy', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('voice_connection_id', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('voice_enabled', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('podcast_settings', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'agents', 'voice_connections', ['voice_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'podcast_settings')
    op.drop_column('agents', 'voice_enabled')
    op.drop_column('agents', 'voice_connection_id')
    op.drop_table('voice_connections')
    # ### end Alembic commands ###
