"""add_mcp_tools_to_agents

Revision ID: 946675892296
Revises: ecc14aa388c1
Create Date: 2025-06-21 05:48:19.593337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946675892296'
down_revision: Union[str, Sequence[str], None] = 'ecc14aa388c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('selected_mcp_tools', sa.JSON(), nullable=True))
    op.add_column('agents', sa.Column('mcp_tool_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'mcp_tool_config')
    op.drop_column('agents', 'selected_mcp_tools')
    # ### end Alembic commands ###
