"""add_mcp_support_to_connections

Revision ID: ecc14aa388c1
Revises: 23539da85f87
Create Date: 2025-06-20 19:15:01.528628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc14aa388c1'
down_revision: Union[str, Sequence[str], None] = '23539da85f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('mcp_server_url', sa.String(length=500), nullable=True))
    op.add_column('connections', sa.Column('mcp_server_config', sa.JSON(), nullable=True))
    op.add_column('connections', sa.Column('available_tools', sa.JSON(), nullable=True))
    op.add_column('connections', sa.Column('mcp_capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'mcp_capabilities')
    op.drop_column('connections', 'available_tools')
    op.drop_column('connections', 'mcp_server_config')
    op.drop_column('connections', 'mcp_server_url')
    # ### end Alembic commands ###
